### ISSUE TITLE
Open source for community contributions?

### ISSUE THREAD

**Issue by vinsibal** [ElliotGarbus/Polymoon-Editor-and-Librarian#1]
Have you considered making these meris apps open source for community contributions?

**Comment by ElliotGarbus** [comment]
Are you interested in contributing?

There are a number of reasons I’ve decided not to open source these projects.

**Comment by vinsibal** [comment]
Yes, I'm definitely interested in contributing.  My preference are for web clients but I don't mind working in windows.

**Comment by ElliotGarbus** [comment]
The code is in Python and uses the Kivy graphics framework and mido library.

What changes did you have in mind?

**Comment by vinsibal** [comment]
Actually I just found a separate meris project that's open source.  They don't have a polymoon editor but it seems like I can update their project to include one.  Cheers.

**Comment by vinsibal** [comment]
As far as changes I had in mind, here are few:

-Allow entering a specific number as a value to a virtual knob (instead of only using a mouse)
-Allow using keyboard shortcuts for changing presets or turning the expression pedal from toe up to toe down
-I'd prefer the layout to be similar to the layout of the physical knobs

**Comment by ElliotGarbus** [comment]
I have decided to not open source this project.  I have open sourced 2 similar projects:
https://github.com/ElliotGarbus/ChaseBlissEditor/releases
https://github.com/ElliotGarbus/MidiClockGenerator
