### ISSUE TITLE
communication on macOS 10.15

### ISSUE THREAD

**Issue by jeremybernstein** [ElliotGarbus/Polymoon-Editor-and-Librarian#2]
Hi, I'm trying to set up the Polymoon editor on my macOS 10.15 machine. Using MIDI Monitor.app, I can observe that the app is communicating with my pedal and that sysex is being passed back and forth; nevertheless, the editor hangs on the "Reading Presets, Writing Name" dialog and never completes. Any tips? Thanks!

**Comment by jeremybernstein** [comment]
I should note that setting parameters from the interface is also working fine -- it's just the state/preset fetching that's not working for me.

**Comment by jeremybernstein** [comment]
Forget it, I had an unconnected TRS cable plugged into another jack on my MIDI I/O box which was generating noise and preventing reliable sysex communication.

**Comment by ElliotGarbus** [comment]
Glad you figured it out.  Enjoy & Stay Healthy!
