### ISSUE TITLE
Polymoon app for Mac

### ISSUE THREAD

**Issue by rinckd** [ElliotGarbus/Polymoon-Editor-and-Librarian#3]
Is the Polymoon app available for mac? In the download section, the HedraEdit.zip is listed instead of the Polymoon.zip. 

![image](https://user-images.githubusercontent.com/546002/132006301-7c7936c7-02f1-4338-9685-184b1909f73d.png)

Really love your work! It makes the Meris pedals come alive in unique ways! Thanks!

**Comment by ElliotGarbus** [comment]
Thanks for letting for me know.  Fixed!
And I'm glad to hear you are enjoying the editors.

**Comment by ralframone** [comment]
Hello - 

I am using a Morningstar MC8 to communicate with my polymoon. It works fine for preset management, comms seem good. I have it on Midi Channel 1.

When I Connect using your app, we get about 80% into the visual bar showing "Reading presets, Writing Names", then the MC8 changes from Bank 02 to Bank 05 and the Polymoon Edit app hangs.

Could be me - but so near, yet so far!

App looks superb, hope it might be something obvious.

**Comment by ElliotGarbus** [comment]
I assume you are connecting the Polymoon to the MC8 with a TRS cable.  This will not work.  The editor requires a bi-directional connection the pedal - MIDI In and Midi Out.  The MC8 only provides midi out on the OMNIPORTs.   You will need a different device to connect the the pedal.  You could use a Meris MIDI I/O and connect to the DIN connections on the MC8, or connect the Meris MIDI I/O to USB to MIDI cable like the Roland UM-One Mk2.    Feel free to ask any follow up questions.

**Comment by ralframone** [comment]
Thank you Elliot for the quick reply. Exactly what I am doing, and  now I understand what the MC8 is up to.

I also have an Electron Digitakt with usb midi and 5 pin out and thru ports, I will grab a cable and try that out - have you come across that combo at all...

Many thanks again!

**Comment by ElliotGarbus** [comment]
I'm not familiar with the Digitakat, looking at the users manual I'm not sure how that will solve your problems.  You need a device that will go from the Meris TRS connector to a MIDI in and Midi out connection.  The Meris MIDI I/O is the simplest device to do this, and does it in a midi compliant way that ensure no ground loops.  Some of the DisasterArea midi controllers, like the qConnect and others can be configured to do this function.  The Strymon Conduit should also work.

**Comment by ralframone** [comment]
Thank you, good explanation. I took the time to properly read the Conduit manual, very good wiring and data flow diagrams at the back of that, showing the differences when a host is provided via USB, versus controller set ups. 
Now I understand better what I bought when I got the MC8! 

Awesome, I'll let you know how I get on.

**Comment by ElliotGarbus** [comment]
I look forward to hearing about your success.

**Comment by braduro** [comment]
Hi! Feel very lucky to join the party here. On my 13” mbp running Catalina and the latest editor, the settings for the generator panel are an unselectable solid white bar I cannot tell if it is working, but it won’t let me check and uncheck items to randomize. I will check it again now that I see the species continue generating even if the cross fader goes fully to the right side after one pass of the generator…

**Comment by ElliotGarbus** [comment]
@braduro That is a strange one.  Please post an image.  I will double check the editor on Catalina in the next few days.
Are you running any kind of virus scanner?  I would expect that behavior is some of the files from the install were missing or corrupted.  I'm wondering if something corrupted the installation.

**Comment by braduro** [comment]
Ah, well I could reinstall. It’s a new computer that migrated the contents of the previous drive. Could be that some things did not carry forward…

**Comment by ElliotGarbus** [comment]
That could be it... could be something is in the wrong place.  Let me know how it works after the reinstall.

**Comment by braduro** [comment]
Hi @ElliotGarbus I'm very grateful that you are actively developing and participating in this. I downloaded the zip file here on GitHub, and it expands into a standalone app, which I then dragged to the applications folder. I'm not sure how an install this straightforward could have extensions or associated files missing. Nonetheless, here's a screenshot of the Generator Settings pop-up window, as per your request
![Screen Shot 85](https://user-images.githubusercontent.com/8356378/148268715-f3c58ee7-aa31-44c8-b497-0abe6ac6e705.jpg)
:

**Comment by ElliotGarbus** [comment]
@braduro Thanks for the follow-up.  I should have time to check later today.  I'll let you know what I find out.

**Comment by ElliotGarbus** [comment]
@braduro Thanks for identifying and reporting this issue.  There was a bug in the build for the mac.  It has been fixed.  Please download the updated version from Github.  Let me know if this fixes the issue for you.

**Comment by braduro** [comment]
That did the trick, thank you @ElliotGarbus  To celebrate, I'll give it a run around the track

**Comment by ElliotGarbus** [comment]
@braduro Enjoy!
