### ISSUE TITLE
Sysex Export and Import faulty in Polymoon, Hedra and Mercury7. Only Enzo works!

### ISSUE THREAD

**Issue by mayasfinest** [ElliotGarbus/Polymoon-Editor-and-Librarian#4]
Hello Elliot,
i have problems with the export and import of sysex presets in 3 of your editors Polymoon, Hedra and Mercury7.
With Enzo everything works as expected,  I am able to export Sysex files of my presets and they are applicable (loadable) in either your Enzo-Editor or in 3rd party software.
When I do an export in one of the "faulty" editors, let's say Hedra, the output file is produced but seems corrupted and even when I re-import it in your own software I get an error window: "Problems with opening or reading file. File is ignored"

Can you reproduce (and evtually fix) the error?

Thanks
Jörg

**Comment by ElliotGarbus** [comment]
I'll take a look.  
Just to ensure I understand the issue.  Is it correct you are exporting the sysex by dragging the patch to the script "syx" at the bottom of the editor screen?

**Comment by ElliotGarbus** [comment]
Never mind, I've found the bug.  
Thanks for reporting it.  I'll get an update out by the end of the week, and I will post here when it is done.

**Comment by mayasfinest** [comment]
Yes, correct, via the sysex Icon. Saving by  dragndrop and loading by clicking.

Von meinem iPhone gesendet

**Comment by mayasfinest** [comment]
Great! And it‘s true for all 3 editors?

Von meinem iPhone gesendet

**Comment by ElliotGarbus** [comment]
I have not checked - but I'm sure it is the same issue.  More that you want to know... Enzo was the first editor I created.  When I started making the others versions I made much of the code common and configurable.   The code to write the sysex has the Enzo model value hard coded in.  It is a quick change.  I'll let you know when it is done.

Thanks for reporting the issue!

**Comment by ElliotGarbus** [comment]
Polymoon, Hedra, Mercury7 and Ottobit Editors updated for Windows and Mac.  Please confirm that this update fixes your issue.

**Comment by mayasfinest** [comment]
Great! Thank you, i did a working export in everything except Ottobit, you can close the issue

 

Von: Elliot Garbus ***@***.***> 
Gesendet: Mittwoch, 26. Januar 2022 23:40
An: ElliotGarbus/Polymoon-Editor-and-Librarian ***@***.***>
Cc: mayasfinest ***@***.***>; Author ***@***.***>
Betreff: Re: [ElliotGarbus/Polymoon-Editor-and-Librarian] Sysex Export and Import faulty in Polymoon, Hedra and Mercury7. Only Enzo works! (Issue #4)

 

Polymoon, Hedra, Mercury7 and Ottobit Editors updated for Windows and Mac. Please confirm that this update fixes your issue.

**Comment by ElliotGarbus** [comment]
Thanks for letting me know.  Issue fixed and closed.
